services:
  db:
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: book_room_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  rails:
    build:
      context: ./rails
      dockerfile: Dockerfile.dev  # ← 明示的に指定
    user: root
    environment:
      RAILS_ENV: development
      BUNDLE_WITHOUT: "" # ← 追加：空文字で上書き
      BUNDLE_DEPLOYMENT: "" # ← 追加：空文字で上書き
      BUNDLE_FROZEN: "false" # ← 追加：frozen mode無効化
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails:/rails
      - bundle_cache:/usr/local/bundle # ← gemの永続化
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

  next:
    build:
      dockerfile: ./next/Dockerfile
    command: npm run dev
    tty: true
    stdin_open: true
    volumes:
      - ./next:/app
    ports:
      - "8000:3000"
    depends_on:
      - rails

volumes:
  mysql_data:
  bundle_cache: # ← gemの永続化
