version: '3'

services:
  db:
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: book_room_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  rails:
    build:
      context: ./rails
    environment:
      RAILS_ENV: development  # 復活     
      # 開発用Dockerfileを指定
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

  next:
        build:
          dockerfile: ./next/Dockerfile
        command: npm run dev  
        tty: true
        stdin_open: true
        volumes:
          - ./next:/app
        ports:
          - "8000:3000"
        depends_on:
          - rails  # ← SSRでRails APIを使うため必要。必ずrailsが起動してからNext.jsを起動する          


volumes:
  mysql_data: