default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  port: 3306

development:
  <<: *default
  host: db   # dbは、docker-compose.ymlで定義したMySQLサービスのサービス名
  database: book_room_development
  password: password

test:
  <<: *default
  host: db  
  database: book_room_test
  password: password  
