default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db    # dbは、docker-compose.ymlで定義したMySQLサービスのサービス名
  port: 3306

development:
  <<: *default
  database: book_room_development

test:
  <<: *default
  database: book_room_test

production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>